INSERT INTO TB_COMM_CODE VALUES ('TR_TYPE', '01', '입금',     1, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('TR_TYPE', '02', '출금',     2, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('TR_TYPE', '03', '이체',     3, 'Y');

INSERT INTO TB_COMM_CODE VALUES ('ACCT_ST', '01', '정상',     1, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('ACCT_ST', '02', '해지',     2, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('ACCT_ST', '03', '거래정지', 3, 'Y');

INSERT INTO TB_COMM_CODE VALUES ('BANK',    '012', '문범저축은행', 1, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('BANK',    '013', '가나저축은행', 2, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('BANK',    '014', '다라저축은행', 3, 'Y');

INSERT INTO TB_COMM_CODE VALUES ('CNCL_RSN', '01', '금액오입력',   1, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('CNCL_RSN', '02', '계좌오입력',   2, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('CNCL_RSN', '03', '고객요청',     3, 'Y');

INSERT INTO TB_EMP VALUES ('E12345', '서문범', '012', '0001', '1234', '01', 'Y');
INSERT INTO TB_EMP VALUES ('E99999', '박책임', '012', '0001', '1234', '09', 'Y');
INSERT INTO TB_EMP VALUES ('E54321', '이담당', '013', '0002', '1234', '01', 'Y');

INSERT INTO TB_COMM_CODE VALUES ('AUTH_LV', '01', '담당자', 1, 'Y');
INSERT INTO TB_COMM_CODE VALUES ('AUTH_LV', '09', '책임자', 2, 'Y');

INSERT INTO TB_BIZ_DATE VALUES ('20260914', 'Y', 'Y', NULL);
INSERT INTO TB_BIZ_DATE VALUES ('20260915', 'Y', 'N', NULL);
INSERT INTO TB_BIZ_DATE VALUES ('20260916', 'Y', 'N', NULL);
INSERT INTO TB_BIZ_DATE VALUES ('20260917', 'Y', 'N', NULL);
INSERT INTO TB_BIZ_DATE VALUES ('20260918', 'Y', 'N', NULL);
INSERT INTO TB_BIZ_DATE VALUES ('20260919', 'N', 'N', '토요일');
INSERT INTO TB_BIZ_DATE VALUES ('20260920', 'N', 'N', '일요일');
INSERT INTO TB_BIZ_DATE VALUES ('20260921', 'Y', 'N', NULL);

INSERT INTO TB_MENU VALUES ('M001', '입금',     '/deposit.html', '01', 1, 'Y');
INSERT INTO TB_MENU VALUES ('M002', '거래내역', '/history.html', '01', 2, 'Y');
INSERT INTO TB_MENU VALUES ('M003', '거래취소', '/cancel.html',  '09', 3, 'Y');