CREATE TABLE TB_TR_HIST (
    TR_NO        VARCHAR(12)   NOT NULL,
    BANK_CODE    VARCHAR(3),
    BRANCH_CODE  VARCHAR(4),
    EMP_NO       VARCHAR(6),
    TR_CODE      VARCHAR(8),
    TR_DATE      VARCHAR(8),
    TR_TIME      VARCHAR(6),
    ACCT_NO      VARCHAR(14),
    CUST_NM      VARCHAR(20),
    AMOUNT       NUMBER(15),
    BALANCE      NUMBER(15),
    RES_CODE     VARCHAR(4),
    RES_MSG      VARCHAR(100),
    REG_DTM      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TR_NO)
);

CREATE TABLE TB_COMM_CODE (
    GRP_CODE     VARCHAR(10)  NOT NULL,
    CODE         VARCHAR(10)  NOT NULL,
    CODE_NM      VARCHAR(50),
    SORT_ORD     NUMBER(3),
    USE_YN       VARCHAR(1)   DEFAULT 'Y',
    PRIMARY KEY (GRP_CODE, CODE)
);

CREATE TABLE TB_EMP (
    EMP_NO       VARCHAR(6)   NOT NULL,
    EMP_NM       VARCHAR(20),
    BANK_CODE    VARCHAR(3),
    BRANCH_CODE  VARCHAR(4),
    PASSWD       VARCHAR(100),
    AUTH_LV      VARCHAR(2),
    USE_YN       VARCHAR(1) DEFAULT 'Y',
    PRIMARY KEY (EMP_NO)
);

CREATE TABLE TB_BIZ_DATE (
    BASE_DATE    VARCHAR(8)  NOT NULL,
    BIZ_YN       VARCHAR(1),
    CLOSE_YN     VARCHAR(1)  DEFAULT 'N',
    HOLIDAY_NM   VARCHAR(50),
    PRIMARY KEY (BASE_DATE)
);

CREATE TABLE TB_MENU (
    MENU_ID      VARCHAR(10)  NOT NULL,
    MENU_NM      VARCHAR(50),
    MENU_URL     VARCHAR(100),
    AUTH_LV      VARCHAR(2),
    SORT_ORD     NUMBER(3),
    USE_YN       VARCHAR(1) DEFAULT 'Y',
    PRIMARY KEY (MENU_ID)
);


CREATE TABLE TB_CASH (
    BASE_DATE    VARCHAR(8)  NOT NULL,
    BRANCH_CODE  VARCHAR(4)  NOT NULL,
    EMP_NO       VARCHAR(6)  NOT NULL,
    START_AMT    NUMBER(15)  DEFAULT 0,
    REAL_AMT     NUMBER(15)  DEFAULT 0,
    CLOSE_YN     VARCHAR(1)  DEFAULT 'N',
    CLOSE_DTM    TIMESTAMP,
    PRIMARY KEY (BASE_DATE, BRANCH_CODE, EMP_NO)
);

CREATE TABLE TB_ACCOUNT (
    ACCT_NO      VARCHAR(14) NOT NULL,
    BANK_CODE    VARCHAR(3),
    CUST_NM      VARCHAR(20),
    PROD_NM      VARCHAR(30),
    PASSWD       VARCHAR(100),
    BALANCE      NUMBER(15) DEFAULT 0,
    ACCT_STATUS  VARCHAR(2) DEFAULT '01',
    PRIMARY KEY (ACCT_NO)
);