CREATE TABLE TB_TR_HIST (
    TR_NO        VARCHAR(12)   NOT NULL,
    BANK_CODE    VARCHAR(3),
    BRANCH_CODE  VARCHAR(4),
    EMP_NO       VARCHAR(6),
    TR_CODE      VARCHAR(8),
    TR_DATE      VARCHAR(8),
    TR_TIME      VARCHAR(6),
    ACCT_NO      VARCHAR(14),
    CUST_NM      VARCHAR(20),
    AMOUNT       NUMBER(15),
    BALANCE      NUMBER(15),
    RES_CODE     VARCHAR(4),
    RES_MSG      VARCHAR(100),
    REG_DTM      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TR_NO)
);